"""Validate Phase 8 catalogs and run tests in the isolated Gateway uv project."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "phase8"


def load(name: str) -> dict:
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def validate_catalogs() -> None:
    source = load("source-compiler-vectors.json")
    runtime = load("cross-runtime-categories.json")
    faults = load("fault-recovery-matrix.json")
    rollout = load("rollout-capability-matrix.json")
    regression = load("regression-matrix.json")
    surface = load("public-surface-phase7.json")

    if source["adapter_status"] != "blocked_pending_integration":
        raise SystemExit("source/compiler adapter status must be explicit")
    if runtime["rules"]["lt_write_default"] != "off":
        raise SystemExit("LT write must stay default-off")
    if runtime["rules"]["ezdxf_live_dwg_authority"] is not False:
        raise SystemExit("ezdxf cannot be live DWG authority")
    if any(case["may_reexecute"] for case in faults["cases"]):
        raise SystemExit("recovery matrix cannot authorize write re-execution")
    if any(item["effective_write"] for item in rollout["capability_admission"]):
        raise SystemExit("Phase 8 capability matrix cannot enable write yet")
    if any(item["enabled"] for item in rollout["extension_packs"]):
        raise SystemExit("Phase 8 extension packs must remain disabled")
    if len(surface["tools"]) != 10 or len(surface["resources"]) != 16:
        raise SystemExit("Phase 7 public snapshot count changed")
    if surface["security_control"] != "S8-010":
        raise SystemExit("public snapshot must be bound to security control S8-010")

    print(
        "Phase 8 conformance catalogs valid: "
        f"{len(source['vectors'])} source/compiler vectors, "
        f"{len(runtime['fixture_categories'])} cross-runtime fixture categories, "
        f"{len(faults['cases'])} fault cases, "
        f"{len(rollout['slices'])} rollout slices, "
        f"{len(regression['suites'])} regression suites.",
        flush=True,
    )
    print(
        "Compiler adapter: blocked_pending_integration (not executed).",
        flush=True,
    )
    print("Live AutoCAD evidence: not generated by this command.", flush=True)


def run_gateway_tests() -> int:
    command = [
        "uv",
        "run",
        "--project",
        str(ROOT / "services" / "gateway"),
        "python",
        "-m",
        "pytest",
        "-q",
        "tests/phase8",
        "--basetemp=.pytest_cache/phase8-conformance",
    ]
    print(
        "Running Phase 8 tests in the isolated Gateway uv environment.",
        flush=True,
    )
    completed = subprocess.run(command, cwd=ROOT, check=False)
    return completed.returncode


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--catalogs-only",
        action="store_true",
        help="Validate JSON catalogs without launching pytest.",
    )
    args = parser.parse_args()

    validate_catalogs()
    if not args.catalogs_only:
        return run_gateway_tests()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
